language: go

sudo: required
ㄇㄇㄇ

services:
  - docker

env:
  - CHANGE_MINIKUBE_NONE_USER=true

before_install:
  - go get -u github.com/kardianos/govendor

before_script:
  - sudo mount --make-rshared /
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - sudo minikube start --vm-driver=none --bootstrapper=localkube --kubernetes-version=v1.9.0 --extra-config=apiserver.Authorization.Mode=RBAC
  - minikube update-context
  - until kubectl get nodes | grep -i `hostname` | grep Ready;do sleep 1; done
  - until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="{.items[0].status.phase}" | grep "Running" ;do sleep 1;echo "waiting for kube-addon-manager to be available"; kubectl get pods --all-namespaces; done

script:
  - go test -v ./...
